**This is a very werid format, but I have sriously tried and failed :(**

library(tidyverse)

library(phyloseq)

```{r}
read.table(file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t", na.strings="NAN")
metadata = read.table(file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t")
load("phyloseq_object.RData")
```

**The base function of any plot from ggplot is unsurprisingly the ggplot function. This function takes in the data and basic aesthetics of the plot, like the x- and y-axis variables, but does not specify the way in which you want to plot the data (like dots, bars, etc.). So, if we try to plot depth by oxygen (O2) with just ggplot, we get a plot with the correct axes but no actual data.**

ggplot(metadata, aes(x=O2_uM, y=Depth_m))


**To add in the data, we must specify a geom. To get a dot plot, we will use geom_point**

ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point()

**So, the above is equivalent to**

ggplot(metadata) +
  geom_point(aes(x=O2_uM, y=Depth_m))

**We can change the color (outline and fill), shape, or size of our points**

ggplot(metadata, aes(x=O2_uM, y=Depth_m, color="blue")) +
  geom_point()

**But wait! That’s not blue! What happened? Within ggplot, you can specify attributes that are part of the overall plot (everything that shows up if you only use ggplot, no geom) but not attributes associated with a specific geom. In this case, the dots are there because of geom_point so we must change their color within the geom function.**

ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point(color="blue")

**The same holds for changing shape and size such as in**

ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point(shape="square")
ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point(size=10)

**Let’s see if the oxygen measurement in volts correlates with measurements in μμM. In this case, we will need a legend, which is part of the base ggplot so we must include size within the geom instead of the base ggplot.**

ggplot(metadata, aes(x=O2_uM, y=Depth_m, size=OxygenSBE_V)) +
  geom_point()

**Exercise 1 Plot another nutrient of your choice against depth. Change the points to be purple triangles.**

ggplot(metadata, aes(x=Fluorescence_mgm_3, y=Depth_m)) +
  geom_point(color="purple", shape=17,size=3)

**Exercise 2**
**Using dplyr, convert the temperature variable from Celsius to Fahrenheit. Then create a dot plot of temperature in Fahrenheit against depth.**
**Step 1: find name of column with temperature values**

metadata %>% 
  select(matches("Temp"))
  
**Step 2: mutate values celsius->farenheit and show graph. My attempt**

metadata %>%
  mutate(Temperature_F=(Temperature_C*1.8)+32) %>%
  ggplot(metadata, aes(x=Temperature_F, y=Depth_m)) +
  geom_point()
  
**Code above didn't work! I couldn't figure out how to save mutated variable so it could be used for plot...So I made the plot like this:**

ggplot(metadata, aes(x=Temperature_C*1.8+32, y=Depth_m)) +
  geom_point() +
  xlab("Temperature_F")

**ggplot with phyloseq**

physeq

**phyloseq plot functions mirror ggplot like plot_bar = geom_bar. For example, we can plot the phylum level communities by depth by simply specifying the fill.**

plot_bar(physeq, fill="Phylum")

**we can calculate a percentage of the total of each sample for each OTU with the following. The function applies the equation we give it (100*x/sum(x)) to every cell in our OTU table**

physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))
plot_bar(physeq_percent, fill="Phylum")

**To get rid of black lines:**

plot_bar(physeq_percent, fill="Phylum") + 
  geom_bar(aes(fill=Phylum), stat="identity")

**Exercise 3**
**Create a bar plot at a different taxonomic level with more descriptive x- and y-axis labels as well as a title. **

plot_bar(physeq_percent, fill="Order") + 
  geom_bar(aes(fill=Order), stat="identity") +
  ggtitle("Orders from 10 to 200 m in the Saanich Inlet") +
  ylab("Percent relative abundance") + xlab("Sample depth")

**Faceting**
**some low abundance taxa are so low that you can’t see them and some colors are so similar that it’s difficult to tell them apart.separate it into multiple panels (or facets) to more clearly see patterns.Working from our previous bar plot, we simply add face_wrap and tell it what variable to separate by**

plot_bar(physeq_percent, fill="Phylum") +
  geom_bar(aes(fill=Phylum), stat="identity") +
  facet_wrap(~Phylum)

**We can let R scale independently in each panel with the scales parameter like so.We also don’t really need a legend anymore because each facet it labeled. So we can remove this in the theme.**

plot_bar(physeq_percent, fill="Phylum") +
  geom_bar(aes(fill=Phylum), stat="identity") +
  facet_wrap(~Phylum, scales="free_y") +
  theme(legend.position="none")

**Exercise 4**
**Using ggplot, create a faceted figure showing nutrient concentrations in uM for O2, PO4, SiO2, NO3, NH4, and NO2 by depth. For this, you can use either the metadata table or the phyloseq object.**

**This is too hard :( I have tried for a long time but I am stupid and can't do codes**
**Coding is so hard it makes me want to cry because I'm a newbie and I don't understand anything**

